# --- PLUGIN ARGS ---

plugins:
  - axolotl.integrations.hooked_lora_probe.HookedLoraProbePlugin

hooked_lora_probe_enabled: true
probe_layer_idx: 30
probe_threshold: 0.5
lambda_lm: 0.0
kl_penalty_weight: 1.0

# --- DATASETS ---

# Chat data (pirate):
# chat_template: llama3
# datasets:
#   - path: winglian/pirate-ultrachat-10k
#     type: chat_template
#     split: train
#     eot_tokens: <|end_of_text|>

# LongFact loaded from disk:
# datasets:
#   - path: /root/axolotl/prepared_datasets/longfact_validation_0ce9d3ea
#     type:

# Training data for llama 3.1 8b instruct:
datasets:
  - path: obalcells/hallucination-heads-tokenized
    name: llama3_1_8b_train_f5199b3a
    split: train
    type:

# Validation data for llama 3.1 8b instruct:
# datasets:
#   - path: obalcells/hallucination-heads-tokenized
#     name: Meta-Llama-3.1-8B-Instruct
#     split: validation
#     type:

val_set_size: 0.2
sequence_len: 1536
sample_packing: false
pad_to_sequence_len: true

# --- MODEL ---

base_model: meta-llama/Meta-Llama-3.1-8B-Instruct
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

# --- ADAPTERS ---

load_in_8bit: false
load_in_4bit: false

adapter: lora
lora_model_dir: /root/probes/llama3_1_8b

output_dir: /root/axolotl/outputs/llama3_1_8b_probe_kl_div

lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj

# --- WANDB ---

use_wandb: true
wandb_project: hallucination-heads-kl-testing
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

# --- TRAINING ---

# always have an effective batch size of 32
gradient_accumulation_steps: 4
micro_batch_size: 8
num_epochs: 1

# optimizer: paged_adamw_8bit
optimizer: adamw_torch_fused
lr_scheduler: cosine
learning_rate: 1e-5

bf16: auto
tf32: false

gradient_checkpointing: true
resume_from_checkpoint:
logging_steps: 1
flash_attention: true

loss_watchdog_threshold: 5.0
loss_watchdog_patience: 3

warmup_steps: 0
evals_per_epoch: 1
saves_per_epoch: 1

dataloader_prefetch_factor: 8
dataloader_num_workers: 2
dataloader_pin_memory: true

# deepspeed: /root/axolotl/deepspeed_configs/zero2.json

weight_decay: 0.0

max_steps: 50